/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Estudio;
import Clases.FunctionTXT;


/**
 *
 * @author georg
 */
public class Interfaz_principal extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    
    public static Global global;
    
    public Interfaz_principal(Global global) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.global = global;
        jSpinnerAnimadoresDisney.setValue(global.getDisney().getAnimadores().getTrabajadores());
        jSpinnerAnimadoresCartoon.setValue(global.getDisney().getAnimadores().getTrabajadores());
        jSpinnerDisenadoresDisney.setValue(global.getDisney().getDiseñadores().getTrabajadores());
        jSpinnerDisenadoresCartoon.setValue(global.getDisney().getDiseñadores().getTrabajadores()); 
        jSpinnerActoresDisney.setValue(global.getDisney().getActores().getTrabajadores());
        jSpinnerActoresCartoon.setValue(global.getDisney().getActores().getTrabajadores());
        jSpinnerEnsambladoresDisney.setValue(global.getDisney().getEnsambladores().getTrabajadores());
        jSpinnerEnsambladoresCartoon.setValue(global.getDisney().getEnsambladores().getTrabajadores());
        jSpinnerGuionistaDisney.setValue(global.getDisney().getGuionistas().getTrabajadores());
        jSpinnerGuionistasCartoon.setValue(global.getDisney().getGuionistas().getTrabajadores());
        jSpinnerPlotTwistDisney.setValue(global.getDisney().getPlotTwist().getTrabajadores());
        jSpinnerPlotTwistCartoon.setValue(global.getDisney().getPlotTwist().getTrabajadores());
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Inicio = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Actualizar = new javax.swing.JButton();
        jSpinnerDuracion = new javax.swing.JSpinner();
        jSpinnerDeadline = new javax.swing.JSpinner();
        jSpinnerGuionistaDisney = new javax.swing.JSpinner();
        jSpinnerDisenadoresDisney = new javax.swing.JSpinner();
        jSpinnerAnimadoresDisney = new javax.swing.JSpinner();
        jSpinnerActoresDisney = new javax.swing.JSpinner();
        jSpinnerPlotTwistDisney = new javax.swing.JSpinner();
        jSpinnerEnsambladoresDisney = new javax.swing.JSpinner();
        jSpinnerGuionistasCartoon = new javax.swing.JSpinner();
        jSpinnerDisenadoresCartoon = new javax.swing.JSpinner();
        jSpinnerAnimadoresCartoon = new javax.swing.JSpinner();
        jSpinnerActoresCartoon = new javax.swing.JSpinner();
        jSpinnerPlotTwistCartoon = new javax.swing.JSpinner();
        jSpinnerEnsambladoresCartoon = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        DisneyChanel = new javax.swing.JPanel();
        CartoonNetwork = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        WorkStatus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        faltas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Dashboard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Dashboard.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        jSpinnerDuracion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        Dashboard.add(jSpinnerDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 90, -1));

        jSpinnerDeadline.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        Dashboard.add(jSpinnerDeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 90, -1));

        jSpinnerGuionistaDisney.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        Dashboard.add(jSpinnerGuionistaDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jSpinnerDisenadoresDisney.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        Dashboard.add(jSpinnerDisenadoresDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jSpinnerAnimadoresDisney.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        Dashboard.add(jSpinnerAnimadoresDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jSpinnerActoresDisney.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        Dashboard.add(jSpinnerActoresDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jSpinnerPlotTwistDisney.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        Dashboard.add(jSpinnerPlotTwistDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jSpinnerEnsambladoresDisney.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        Dashboard.add(jSpinnerEnsambladoresDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jSpinnerGuionistasCartoon.setModel(new javax.swing.SpinnerNumberModel(1, 1, 18, 1));
        Dashboard.add(jSpinnerGuionistasCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jSpinnerDisenadoresCartoon.setModel(new javax.swing.SpinnerNumberModel(1, 1, 18, 1));
        Dashboard.add(jSpinnerDisenadoresCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jSpinnerAnimadoresCartoon.setModel(new javax.swing.SpinnerNumberModel(1, 1, 18, 1));
        Dashboard.add(jSpinnerAnimadoresCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jSpinnerActoresCartoon.setModel(new javax.swing.SpinnerNumberModel(1, 1, 18, 1));
        Dashboard.add(jSpinnerActoresCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jSpinnerPlotTwistCartoon.setModel(new javax.swing.SpinnerNumberModel(1, 1, 18, 1));
        Dashboard.add(jSpinnerPlotTwistCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jSpinnerEnsambladoresCartoon.setModel(new javax.swing.SpinnerNumberModel(1, 1, 18, 1));
        Dashboard.add(jSpinnerEnsambladoresCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1(!).png"))); // NOI18N
        Dashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Inicio.addTab("Inicio", Dashboard);

        javax.swing.GroupLayout DisneyChanelLayout = new javax.swing.GroupLayout(DisneyChanel);
        DisneyChanel.setLayout(DisneyChanelLayout);
        DisneyChanelLayout.setHorizontalGroup(
            DisneyChanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        DisneyChanelLayout.setVerticalGroup(
            DisneyChanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        Inicio.addTab("Disney Chanel", DisneyChanel);

        CartoonNetwork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CartoonNetwork.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel2.setText("Project Manager");
        CartoonNetwork.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 109, 140, -1));

        WorkStatus.setText("jTextField1");
        WorkStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkStatusActionPerformed(evt);
            }
        });
        CartoonNetwork.add(WorkStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel4.setText("WorkStatus");
        CartoonNetwork.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        faltas.setText("jTextField1");
        faltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faltasActionPerformed(evt);
            }
        });
        CartoonNetwork.add(faltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel5.setText("Cant de faltas");
        CartoonNetwork.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        Inicio.addTab("Cartoon Network", CartoonNetwork);

        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WorkStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkStatusActionPerformed

    private void faltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faltasActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        
        Estudio disney = this.global.getDisney();
        Estudio cartoon = this.global.getCartoon();
        
        disney.getAnimadores().setTrabajadores((int)jSpinnerAnimadoresDisney.getValue());
        cartoon.getAnimadores().setTrabajadores((int)jSpinnerAnimadoresCartoon.getValue());
        disney.getDiseñadores().setTrabajadores((int)jSpinnerDisenadoresDisney.getValue());
        cartoon.getDiseñadores().setTrabajadores((int)jSpinnerDisenadoresCartoon.getValue());
        disney.getActores().setTrabajadores((int)jSpinnerActoresDisney.getValue());
        cartoon.getActores().setTrabajadores((int)jSpinnerActoresCartoon.getValue());
        disney.getEnsambladores().setTrabajadores((int)jSpinnerEnsambladoresDisney.getValue());
        cartoon.getEnsambladores().setTrabajadores((int)jSpinnerEnsambladoresCartoon.getValue());
        disney.getGuionistas().setTrabajadores((int)jSpinnerGuionistaDisney.getValue());
        cartoon.getGuionistas().setTrabajadores((int)jSpinnerGuionistasCartoon.getValue());
        disney.getPlotTwist().setTrabajadores((int)jSpinnerPlotTwistDisney.getValue());
        cartoon.getPlotTwist().setTrabajadores((int)jSpinnerPlotTwistCartoon.getValue());
        
        
        this.global.getS().escribir_txt((Estudio)this.global.getDisney());
       
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_principal(global).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JPanel CartoonNetwork;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel DisneyChanel;
    private javax.swing.JTabbedPane Inicio;
    private javax.swing.JTextField WorkStatus;
    private javax.swing.JTextField faltas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinnerActoresCartoon;
    private javax.swing.JSpinner jSpinnerActoresDisney;
    private javax.swing.JSpinner jSpinnerAnimadoresCartoon;
    private javax.swing.JSpinner jSpinnerAnimadoresDisney;
    private javax.swing.JSpinner jSpinnerDeadline;
    private javax.swing.JSpinner jSpinnerDisenadoresCartoon;
    private javax.swing.JSpinner jSpinnerDisenadoresDisney;
    private javax.swing.JSpinner jSpinnerDuracion;
    private javax.swing.JSpinner jSpinnerEnsambladoresCartoon;
    private javax.swing.JSpinner jSpinnerEnsambladoresDisney;
    private javax.swing.JSpinner jSpinnerGuionistaDisney;
    private javax.swing.JSpinner jSpinnerGuionistasCartoon;
    private javax.swing.JSpinner jSpinnerPlotTwistCartoon;
    private javax.swing.JSpinner jSpinnerPlotTwistDisney;
    // End of variables declaration//GEN-END:variables
}
